--- # EC2 Example playbook to lanch instance
- hosts: aws
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - ~/cred.yml
  tasks:
  - name: Basic provisioning of EC2 instance
    ec2:
      aws_access_key: "{{aws_key}}"
      aws_secret_key: "{{aws_id}}"
      region: "{{aws_region}}"
      image: ami-0912f71e06545ad88
      instance_type: t2.micro
      count: 1
      instance_tags: 
       Name: 'del'
    register: result
  - name: Display instance ID
    debug: var=result.instances[0].id

