--- # EC2 Example playbook to lanch instance
- hosts: aws
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - ~/cred.yml
  tasks:
  - name: Basic provisioning of EC2 instance
    ec2:
      aws_access_key: "{{aws_key}}"
      aws_secret_key: "{{aws_id}}"
      region: "{{aws_region}}"
      instance_id: "{{instance_id}}"
      state: absent
    register: result
  - name: Display instance ID
    debug: var=result

